import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Chat Firebase</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="text-4xl font-bold">Home</div>
		</div>
	);
}
