import Head from 'next/head'
import Chat from '../components/Chat'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chat Firebase</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-[#a7bcff] h-[100vh] flex items-center justify-center'>
        <div className='bg-white overflow-hidden rounded-lg w-[60%] h-[85%] flex justify-between flex-row'>
          <Sidebar />
          <Chat />
        </div>
      </div>
    </div>
  )
}
